version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./backend:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 13060:3306

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
      - minio-data:/export
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: server /export --console-address ":9001"

volumes:
  db-store:
  minio-data:
